### ISSUE TITLE
invoking animatedPosition: Logger is not defined

### ISSUE THREAD

**Issue by jerroydmoore** [screepers/RoomVisual#6]
To reproduce:

main.js:
```
require('RoomVisual');
module.exports.loop = function () {
    for(let roomName in Game.rooms) {
        let room = Game.rooms[roomName];
        room.visual.animatedPosition(12, 32)
    }
}
```
In the Console:

```
ReferenceError: Logger is not defined
    at RoomVisual.animatedPosition (RoomVisual:404:5)
    at Object.module.exports.loop (main:34:21)
    at __mainLoop:1:52
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
```

**Comment by AlinaNova21** [comment]
Fixed :)
